# JetBrains IDE flicker / tooltip / tab-drag fixes
windowrule { 
	name = fixintellij
	match:class = jetbrains-idea
	no_initial_focus = on
}

# Picture in picture
windowrule {
	name = pip
	match:title = ^Picture-in-Picture$
	float = on
	no_anim = on
	size = 600 340
	move = 1310 730
}
